"""
Compile knot-region and volume-Dice summary CSV files into one LaTeX table.

The script reads the long-format tables generated by the knot-profile analysis:
  tables/region_analysis/knot_region_summary_long.csv
  tables/volume_analysis/volume_dice_summary_long.csv
"""

import csv
import math
import os


# ---------------------------------------------------------------------------
# Preamble: edit these settings when changing table content
# ---------------------------------------------------------------------------

ROOT_OUT = "/home/aime/monai/Postprocessing/LPDseg_final"

REGION_SUMMARY_CSV = os.path.join(
    ROOT_OUT,
    "tables",
    "region_analysis",
    "knot_region_summary_long.csv",
)
VOLUME_SUMMARY_CSV = os.path.join(
    ROOT_OUT,
    "tables",
    "volume_analysis",
    "volume_dice_summary_long.csv",
)
LATEX_OUT = os.path.join(
    ROOT_OUT,
    "tables",
    "latex",
    "knot_region_and_volume_dice.tex",
)

# Add "val" here when validation results are available.
DATASETS = ["test"]

# Remove size classes here for a shorter table.
SIZE_CATEGORIES = ["all", "small", "medium", "large"]

# "normed" gives every knot group equal length before aggregation.
# Change to "raw" to use the raw-profile region summaries.
PROFILE_TYPE = "normed"

REGION_ORDER = ["Start", "Mid", "End", "Total"]
AGGREGATE_SCOPE = "all_logs"
AGGREGATE_LOG_ID = "ALL"
DECIMALS = 3
FAIL_ON_MISSING = True
MISSING_VALUE = r"\textemdash"

DATASET_LABELS = {
    "test": "Test",
    "val": "Val",
}
SIZE_LABELS = {
    "all": "All",
    "small": "Small",
    "medium": "Medium",
    "large": "Large",
}
REGION_LABELS = {
    "Start": "Start",
    "Mid": "Mid",
    "End": "End",
    "Total": "Total",
}

# The grouped headers and model order are controlled here.
COLUMN_GROUPS = [
    {
        "label": "CT",
        "columns": [
            ("CT", "CT"),
            ("CT-new", "CT-new"),
        ],
    },
    {
        "label": "5 src. pos.",
        "columns": [
            ("5src-LPD-seq", "Sequential"),
            ("5src-LPD-jnt", "Joint"),
        ],
    },
    {
        "label": "10 src. pos.",
        "columns": [
            ("10src-LPD-seq", "Sequential"),
            ("10src-LPD-jnt", "Joint"),
        ],
    },
]

# "All" uses exact full-volume Dice. Size-specific rows use pooled 3D Dice
# within the GT knot-group slice spans assigned to that size class.
VOLUME_DOMAIN_BY_SIZE = {
    "all": "full_volume",
    "small": "gt_knot_group_spans",
    "medium": "gt_knot_group_spans",
    "large": "gt_knot_group_spans",
}
VOLUME_ROW_LABELS = {
    "all": "3D full",
    "small": "3D pooled",
    "medium": "3D pooled",
    "large": "3D pooled",
}

TABLE_CAPTION = (
    "Mean normalized slice-wise Dice scores for knot segmentation at "
    "different positions within knot groups: the first 20\\% (Start), "
    "the middle 60\\% (Mid), the last 20\\% (End), and the complete "
    "normalized knot profile (Total). Results are shown for all knot "
    "groups and for GT-volume terciles classified as small, medium, and "
    "large. The 3D row for All reports exact full-volume pooled Dice "
    "over all selected logs. Size-specific 3D rows report pooled Dice "
    "within the corresponding GT knot-group slice spans. Normalized "
    "profile summaries give each knot group equal weight, whereas pooled "
    "3D Dice weights voxels through the summed intersections and volumes."
)
TABLE_LABEL = "tab:knot-regions-volume-dice"


# ---------------------------------------------------------------------------
# CSV parsing
# ---------------------------------------------------------------------------

def read_csv_rows(path, required_columns):
    if not os.path.isfile(path):
        raise FileNotFoundError(f"Input table not found: {path}")

    with open(path, newline="") as handle:
        reader = csv.DictReader(handle)
        fieldnames = set(reader.fieldnames or [])
        missing_columns = sorted(set(required_columns) - fieldnames)
        if missing_columns:
            raise ValueError(
                f"{path} is missing required columns: {missing_columns}"
            )
        return list(reader)


def parse_optional_float(value):
    if value in (None, ""):
        return None

    parsed = float(value)
    if math.isnan(parsed):
        return None
    return parsed


def insert_unique(lookup, key, value, source_name):
    if key not in lookup:
        lookup[key] = value
        return

    previous = lookup[key]
    if previous is None and value is None:
        return
    if previous is None or value is None:
        raise ValueError(
            f"Conflicting duplicate rows for {key} in {source_name}"
        )
    if not math.isclose(previous, value, rel_tol=1e-12, abs_tol=1e-12):
        raise ValueError(
            f"Conflicting duplicate rows for {key} in {source_name}: "
            f"{previous} versus {value}"
        )


def load_region_lookup(path):
    required_columns = {
        "aggregate_scope",
        "dataset",
        "log_id",
        "size_category",
        "profile_type",
        "variant",
        "knot_region",
        "mean_dice",
    }
    rows = read_csv_rows(path, required_columns)
    lookup = {}

    for row in rows:
        if row["aggregate_scope"] != AGGREGATE_SCOPE:
            continue
        if row["log_id"] != AGGREGATE_LOG_ID:
            continue
        if row["profile_type"] != PROFILE_TYPE:
            continue

        key = (
            row["dataset"],
            row["size_category"],
            row["knot_region"],
            row["variant"],
        )
        insert_unique(
            lookup,
            key,
            parse_optional_float(row["mean_dice"]),
            path,
        )

    return lookup


def load_volume_lookup(path):
    required_columns = {
        "evaluation_domain",
        "aggregate_scope",
        "dataset",
        "log_id",
        "size_category",
        "variant",
        "volume_dice",
    }
    rows = read_csv_rows(path, required_columns)
    lookup = {}

    for row in rows:
        if row["aggregate_scope"] != AGGREGATE_SCOPE:
            continue
        if row["log_id"] != AGGREGATE_LOG_ID:
            continue

        size_category = row["size_category"]
        expected_domain = VOLUME_DOMAIN_BY_SIZE.get(size_category)
        if expected_domain is None:
            continue
        if row["evaluation_domain"] != expected_domain:
            continue

        key = (
            row["dataset"],
            size_category,
            row["variant"],
        )
        insert_unique(
            lookup,
            key,
            parse_optional_float(row["volume_dice"]),
            path,
        )

    return lookup


# ---------------------------------------------------------------------------
# LaTeX generation
# ---------------------------------------------------------------------------

def flattened_columns():
    return [
        (variant, label)
        for group in COLUMN_GROUPS
        for variant, label in group["columns"]
    ]


def validate_configuration():
    columns = flattened_columns()
    variants = [variant for variant, _ in columns]

    if not columns:
        raise ValueError("COLUMN_GROUPS contains no model columns.")
    if len(variants) != len(set(variants)):
        raise ValueError("A model variant occurs more than once in COLUMN_GROUPS.")

    unknown_size_domains = [
        size_category
        for size_category in SIZE_CATEGORIES
        if size_category not in VOLUME_DOMAIN_BY_SIZE
    ]
    if unknown_size_domains:
        raise ValueError(
            "Missing VOLUME_DOMAIN_BY_SIZE entries for: "
            f"{unknown_size_domains}"
        )

    unknown_volume_labels = [
        size_category
        for size_category in SIZE_CATEGORIES
        if size_category not in VOLUME_ROW_LABELS
    ]
    if unknown_volume_labels:
        raise ValueError(
            "Missing VOLUME_ROW_LABELS entries for: "
            f"{unknown_volume_labels}"
        )


def collect_missing_entries(region_lookup, volume_lookup):
    variants = [variant for variant, _ in flattened_columns()]
    missing = []

    for dataset in DATASETS:
        for size_category in SIZE_CATEGORIES:
            for knot_region in REGION_ORDER:
                for variant in variants:
                    key = (
                        dataset,
                        size_category,
                        knot_region,
                        variant,
                    )
                    if key not in region_lookup:
                        missing.append(
                            "region: "
                            f"dataset={dataset}, size={size_category}, "
                            f"region={knot_region}, variant={variant}"
                        )

            for variant in variants:
                key = (
                    dataset,
                    size_category,
                    variant,
                )
                if key not in volume_lookup:
                    missing.append(
                        "volume: "
                        f"dataset={dataset}, size={size_category}, "
                        f"variant={variant}, "
                        f"domain={VOLUME_DOMAIN_BY_SIZE[size_category]}"
                    )

    return missing


def format_value(value):
    if value is None:
        return MISSING_VALUE
    return f"{value:.{DECIMALS}f}"


def model_value_cells(values):
    return " & ".join(format_value(value) for value in values)


def build_group_header():
    group_cells = []
    cmidrules = []
    column_index = 4

    for group in COLUMN_GROUPS:
        n_columns = len(group["columns"])
        group_cells.append(
            rf"\multicolumn{{{n_columns}}}{{c}}"
            rf"{{\textbf{{\small {group['label']}}}}}"
        )
        cmidrules.append(
            rf"\cmidrule(lr){{{column_index}-{column_index + n_columns - 1}}}"
        )
        column_index += n_columns

    first_row = "& & & " + " & ".join(group_cells) + r" \\"
    second_row = (
        r"\textbf{Dataset} & \textbf{Size} & \textbf{Metric} & "
        + " & ".join(
            rf"\textbf{{\footnotesize {label}}}"
            for _, label in flattened_columns()
        )
        + r" \\"
    )

    return [first_row, " ".join(cmidrules), second_row, r"\midrule"]


def build_body(region_lookup, volume_lookup):
    variants = [variant for variant, _ in flattened_columns()]
    n_table_columns = 3 + len(variants)
    rows_per_size = len(REGION_ORDER) + 1
    rows_per_dataset = rows_per_size * len(SIZE_CATEGORIES)
    lines = []

    for dataset_index, dataset in enumerate(DATASETS):
        first_dataset_row = True

        for size_index, size_category in enumerate(SIZE_CATEGORIES):
            first_size_row = True

            for knot_region in REGION_ORDER:
                dataset_cell = ""
                if first_dataset_row:
                    dataset_cell = (
                        rf"\multirow[t]{{{rows_per_dataset}}}{{*}}"
                        rf"{{\textbf{{{DATASET_LABELS.get(dataset, dataset)}}}}}"
                    )
                    first_dataset_row = False

                size_cell = ""
                if first_size_row:
                    size_cell = (
                        rf"\multirow[t]{{{rows_per_size}}}{{*}}"
                        rf"{{\textbf{{{SIZE_LABELS.get(size_category, size_category)}}}}}"
                    )
                    first_size_row = False

                values = [
                    region_lookup.get(
                        (
                            dataset,
                            size_category,
                            knot_region,
                            variant,
                        )
                    )
                    for variant in variants
                ]

                metric_label = REGION_LABELS.get(knot_region, knot_region)
                lines.append(
                    f"{dataset_cell} & {size_cell} & "
                    rf"\textbf{{{metric_label}}} & "
                    + model_value_cells(values)
                    + r" \\"
                )

            volume_values = [
                volume_lookup.get(
                    (
                        dataset,
                        size_category,
                        variant,
                    )
                )
                for variant in variants
            ]
            lines.append(
                " & & "
                rf"\textbf{{{VOLUME_ROW_LABELS[size_category]}}} & "
                + model_value_cells(volume_values)
                + r" \\"
            )

            if size_index < len(SIZE_CATEGORIES) - 1:
                lines.append(
                    rf"\cmidrule(lr){{2-{n_table_columns}}}"
                )

        if dataset_index < len(DATASETS) - 1:
            lines.append(r"\midrule")

    return lines


def build_latex_table(region_lookup, volume_lookup):
    n_model_columns = len(flattened_columns())
    column_spec = "lll" + ("r" * n_model_columns)

    lines = [
        "% Generated by compile_dice_latex_table.py",
        "% Requires: \\usepackage{booktabs,multirow}",
        r"\begin{table}",
        r"\centering",
        rf"\caption{{{TABLE_CAPTION}}}",
        rf"\label{{{TABLE_LABEL}}}",
        r"\par\medskip",
        r"\renewcommand{\arraystretch}{1.05}",
        r"\setlength{\tabcolsep}{4pt}",
        r"\small",
        rf"\begin{{tabular}}{{{column_spec}}}",
    ]

    lines.extend(build_group_header())
    lines.extend(build_body(region_lookup, volume_lookup))
    lines.extend([
        r"\bottomrule",
        r"\end{tabular}",
        r"\end{table}",
        "",
    ])

    return "\n".join(lines)


def main():
    validate_configuration()

    region_lookup = load_region_lookup(REGION_SUMMARY_CSV)
    volume_lookup = load_volume_lookup(VOLUME_SUMMARY_CSV)

    missing_entries = collect_missing_entries(
        region_lookup,
        volume_lookup,
    )
    if missing_entries and FAIL_ON_MISSING:
        preview = "\n".join(
            f"  - {entry}"
            for entry in missing_entries[:20]
        )
        remaining = len(missing_entries) - 20
        if remaining > 0:
            preview += f"\n  ... and {remaining} more"

        raise ValueError(
            "The selected table configuration has missing CSV entries:\n"
            f"{preview}"
        )

    latex = build_latex_table(
        region_lookup,
        volume_lookup,
    )

    os.makedirs(
        os.path.dirname(LATEX_OUT),
        exist_ok=True,
    )
    with open(LATEX_OUT, "w") as handle:
        handle.write(latex)

    print(f"Wrote LaTeX table: {LATEX_OUT}")
    if missing_entries:
        print(
            f"Inserted {len(missing_entries)} missing-value markers."
        )


if __name__ == "__main__":
    main()