#!/usr/bin/env python3
"""Build a merged LaTeX table for segmentation-only comparisons.

Reads outputs generated by visSeg_joint.py from Postprocessing/LPDseg and
combines slice-wise region means (Start/Mid/End/Total) with full 3D means.
"""

import argparse
import csv
import os
import numpy as np

REGIONS = ["Start", "Mid", "End", "Total"]
VARIANTS = ["CT", "LPD-seq", "LPD-jnt"]
VARIANT_LABELS = {
    "CT": "CT",
    "LPD-seq": "LPD seq.",
    "LPD-jnt": "LPD joint",
}


def discover_datasets(root_out: str, metric: str):
    datasets = []
    for name in sorted(os.listdir(root_out)):
        ds_dir = os.path.join(root_out, name)
        if not os.path.isdir(ds_dir):
            continue
        if os.path.isdir(os.path.join(ds_dir, metric)):
            datasets.append(name)
    return datasets


def load_region_means(root_out: str, dataset: str, metric: str):
    metric_dir = os.path.join(root_out, dataset, metric)
    # Keep same behavior as visSeg_joint.py summary: raw for HDF, normed otherwise.
    csv_name = "region_scores.csv" if metric == "hdf" else "region_scores_normed.csv"
    csv_path = os.path.join(metric_dir, csv_name)
    if not os.path.exists(csv_path):
        raise FileNotFoundError(f"Missing region score file: {csv_path}")

    with open(csv_path, "r", encoding="utf-8") as f:
        reader = csv.reader(f)
        rows = list(reader)
    if len(rows) < 3:
        raise RuntimeError(f"Unexpected region score format in {csv_path}")

    header1 = rows[0]
    header2 = rows[1]
    data_rows = rows[2:]

    col_map = {}
    for i in range(min(len(header1), len(header2))):
        col_map[(header1[i], header2[i])] = i

    out = {variant: {} for variant in VARIANTS}
    for variant in VARIANTS:
        for region in REGIONS:
            col = (variant, region)
            if col not in col_map:
                out[variant][region] = np.nan
                continue
            idx = col_map[col]
            vals = []
            for row in data_rows:
                if idx >= len(row):
                    continue
                raw = row[idx].strip()
                if raw == "" or raw.lower() == "nan":
                    continue
                try:
                    vals.append(float(raw))
                except ValueError:
                    continue
            vals = np.array(vals, dtype=float)
            out[variant][region] = float(np.nanmean(vals)) if vals.size else np.nan
    return out


def load_volume_means(root_out: str, dataset: str, metric: str):
    npy_path = os.path.join(root_out, dataset, f"{dataset}_volumeMetrics.npy")
    if not os.path.exists(npy_path):
        raise FileNotFoundError(f"Missing volume metrics file: {npy_path}")

    data = np.load(npy_path, allow_pickle=True)[()]
    out = {variant: [] for variant in VARIANTS}
    for log_id in data:
        for variant in VARIANTS:
            out[variant].append(data[log_id][variant][metric])
    return {variant: (float(np.nanmean(vals)) if vals else np.nan) for variant, vals in out.items()}


def fmt(x):
    if x is None or (isinstance(x, float) and np.isnan(x)):
        return "--"
    return f"{x:.3f}"


def make_latex(metric: str, datasets, region_summary, volume_summary):
    metric_up = metric.upper() if metric == "hdf" else metric.capitalize()
    cols = "llrrr"
    dataset_labels = {"test": "Test", "val": "Val"}

    lines = []
    lines.append(r"\begin{table}")
    lines.append(
        r"\caption{Mean slice-wise "
        + metric_up
        + r" scores for knot segmentation evaluated at various positions within knot groups on test and validation datasets; the first 20\% (Start), the following 60\% (Mid), and the last 20\% (End) along the lengthwise distance of knot groups, and the slice-wise mean for all knot groups. "
        + r"The lower part shows full 3D bulk mean "
        + metric_up
        + r" scores for knot segmentation. Results compare CT baseline against sequential and joint segmentation pipelines. "
        + r"In 2D slice-wise "
        + metric_up
        + r" scores, each slice is weighted equally, unlike full 3D "
        + metric_up
        + r" scores that emphasize slices with larger segmented areas, so overall values can differ due to metric non-linearity and empty or near-empty slices.}"
    )
    lines.append(r"\label{tab:segpipeline-regions-" + metric + r"}")
    lines.append(r"\par\medskip")
    lines.append(r"\renewcommand{\arraystretch}{1}")
    lines.append(r"\begin{tabular}{" + cols + r"}")
    lines.append(r"\toprule")
    lines.append(r"& & \multicolumn{3}{c}{\textbf{\small Segmentation pipelines}} \\")
    lines.append(r"\cmidrule(lr){3-5}")
    lines.append(
        r"& & \textbf{\small "
        + VARIANT_LABELS["CT"]
        + r"} & \textbf{\small "
        + VARIANT_LABELS["LPD-seq"]
        + r"} & \textbf{\small "
        + VARIANT_LABELS["LPD-jnt"]
        + r"} \\"
    )
    lines.append(r"\midrule")

    for i, ds in enumerate(datasets):
        ds_label = dataset_labels.get(ds, ds.capitalize())
        lines.append(
            r"\multirow[t]{4}{*}{\textbf{" + ds_label + r"}} "
            + r"& \textbf{Start}"
            + " & " + fmt(region_summary[ds]["CT"]["Start"])
            + " & " + fmt(region_summary[ds]["LPD-seq"]["Start"])
            + " & " + fmt(region_summary[ds]["LPD-jnt"]["Start"])
            + r" \\"
        )
        for region in ["Mid", "End", "Total"]:
            lines.append(
                r"& \textbf{" + region + r"}"
                + " & " + fmt(region_summary[ds]["CT"][region])
                + " & " + fmt(region_summary[ds]["LPD-seq"][region])
                + " & " + fmt(region_summary[ds]["LPD-jnt"][region])
                + r" \\"
            )
        if i < len(datasets) - 1:
            lines.append(r"\cline{1-5}")

    lines.append(r"\cline{1-5}")

    # 3D block
    if datasets:
        first_ds = datasets[0]
        first_label = dataset_labels.get(first_ds, first_ds.capitalize())
        lines.append(
            r"\textbf{" + first_label + r"} & "
            + r"\multirow[c]{" + str(len(datasets)) + r"}{*}{\textbf{3D}}"
            + " & " + fmt(volume_summary[first_ds]["CT"])
            + " & " + fmt(volume_summary[first_ds]["LPD-seq"])
            + " & " + fmt(volume_summary[first_ds]["LPD-jnt"])
            + r" \\"
        )
        for ds in datasets[1:]:
            ds_label = dataset_labels.get(ds, ds.capitalize())
            lines.append(
                r"\textbf{" + ds_label + r"} &"
                + " & " + fmt(volume_summary[ds]["CT"])
                + " & " + fmt(volume_summary[ds]["LPD-seq"])
                + " & " + fmt(volume_summary[ds]["LPD-jnt"])
                + r" \\"
            )

    lines.append(r"\bottomrule")
    lines.append(r"\end{tabular}")
    lines.append(r"\end{table}")
    return "\n".join(lines) + "\n"


def main():
    parser = argparse.ArgumentParser(description="Create merged segmentation table from visSeg_joint outputs.")
    parser.add_argument("--metric", default="dice", choices=["dice", "iou", "hdf"], help="Metric to summarize.")
    parser.add_argument("--root", default="/home/aime/monai/Postprocessing/LPDseg", help="Root output directory.")
    parser.add_argument("--out", default=None, help="Output .tex path. Defaults to <root>/summary_table_<metric>_merged.tex")
    args = parser.parse_args()

    datasets = discover_datasets(args.root, args.metric)
    if not datasets:
        raise RuntimeError(f"No dataset folders with metric '{args.metric}' found under {args.root}")

    region_summary = {ds: load_region_means(args.root, ds, args.metric) for ds in datasets}
    volume_summary = {ds: load_volume_means(args.root, ds, args.metric) for ds in datasets}

    latex = make_latex(args.metric, datasets, region_summary, volume_summary)
    out_path = args.out or os.path.join(args.root, f"summary_table_{args.metric}_merged.tex")
    with open(out_path, "w", encoding="utf-8") as f:
        f.write(latex)

    print(f"Wrote merged table to: {out_path}")


if __name__ == "__main__":
    main()
